language: nix
install: travis_wait nix-shell
script: travis_wait nix-build .
after_success: |
  if [[ -n "$GITHUB_API_TOKEN" ]]; then echo "Github token present"; fi
  echo "Current branch: ${TRAVIS_BRANCH}"
  if [[ -n "$GITHUB_API_TOKEN" ]] && [[ "$TRAVIS_BRANCH" = master ]]; then
    cd "$TRAVIS_BUILD_DIR"
    [[ -f Makefile ]] || nix-shell --run "./configure"
    if nix-shell --run "make html"; then
      rm *.log
      git checkout -b gh-pages || git checkout gh-pages
      git add html
      git status
      git -c user.name='travis' -c user.email='travis' commit -m "[auto] [docs] $TRAVIS_COMMIT_MESSAGE"
      git remote add docs "https://siddharthist:${GITHUB_API_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
      git push --quiet --force docs gh-pages
    fi
  fi
